### ISSUE TITLE
Support delivery mechanisms other than workflows

### ISSUE THREAD

**Issue by justinmchase** [justinmchase/deploy-approval-api#1]
When a approval is created instead of always sending it to a workflow, add an abstraction which will allow others to configure other integrations such as emails, teams, etc.

Workflows will remain the default and perhaps the only implementation for the public version but it should be configurable and add-on-able.

#### example `.github/approval.yml`
```yml
groups:
  - id: tier1
    name: Tier 1
    mode: email

  - id: tier2
    name: Tier 2
    mode: teams

environments:
  testing:
    groups:
      - tier1
      - tier2
```
